


```{r}
dir.create("download")
dir.create("download/promoter")

destdir <- "download/promoter/"
```




```{r}
library(tidyverse)
library(readxl)

ids <- c("hayleykim97", 
         "th-kim310",
         "Lelp27",
         "aputron",
         "gpemelianov",
         "yoo-bh",
         "seokjin-oh",
         "treebird19",
         "jinjulee119"
         )
homedirs <- rep("researcheweb ", 9) 

destdir <- "download/"

#i <- 2

# https://github.com/TH-Kim310/researcheweb/raw/main/download/partdb.xlsx

for(i in 1:length(ids)){
  url <-  paste0("https://github.com/", ids[i], "/", "researcheweb", "/raw/main/", destdir, "/partdb.xlsx")
  destfile <- paste0(destdir, ids[i], "_partdb.xlsx")
  tempfile <- paste0(destdir, "temp_", ids[i], "_partdb.xlsx")
  
  
  ## check the rules 
  ## ===============================================
  flag <- TRUE
  try(download.file(url, tempfile, quiet = TRUE))
  if(!file.exists(tempfile)){
    cat(i, ids[i], " No excel file\n")
    flush.console()
  }else{
    tmp <- read_excel(tempfile, sheet = 1, skip = 0, col_names = T)
    igem_cols <- c("id", "team_name", "project", "year", "wiki")
    if(length(names(tmp))==length(igem_cols)){
      if(!isTRUE(all.equal(names(tmp), igem_cols))){
        cat(i, ids[i], " check column names in the igem_team sheet\n")
        flush.console()
        flag <- FALSE
      }
    }else{
      cat(i, ids[i], " check the number of columns in the igem_team sheet\n")
      flush.console()
      flag <- FALSE
    }
    
    tmp <- read_excel(tempfile, sheet = 2, skip = 0, col_names = T)
    igem_cols <- c("id", "BBid", "type", "link", "backbone", "device_id", "team_id", "user")
    if(length(names(tmp))==length(igem_cols)){
      if(!isTRUE(all.equal(names(tmp), igem_cols))){
        cat(i, ids[i], " check column names in the igem_part sheet\n")
        flush.console()
        flag <- FALSE
      }
    }else{
      cat(i, ids[i], " check the number of columns in the igem_part sheet\n")
      flush.console()
      flag <- FALSE
    }
    
    tmp <- read_excel(tempfile, sheet = 3, skip = 0, col_names = T)
    igem_cols <- c("id", "device_name", "part_combination")
    if(length(names(tmp))==length(igem_cols)){
      if(!isTRUE(all.equal(names(tmp), igem_cols))){
        cat(i, ids[i], " check column names in the igem_device sheet\n")
        flush.console()
        flag <- FALSE
      }
    }else{
      cat(i, ids[i], " check the number of columns in the igem_device sheet\n")
      flush.console()
      flag <- FALSE
    }
    
    tmp <- read_excel(tempfile, sheet = 4, skip = 0, col_names = T)
    igem_cols <- c("id", "strain", "indc", "concunit", "value", "valunit", "incubhr", "incubtemp", "device_id", "link")
    if(length(names(tmp))==length(igem_cols)){
      if(!isTRUE(all.equal(names(tmp), igem_cols))){
        cat(i, ids[i], " check column names in the igem_obs sheet\n")
        flush.console()
        flag <- FALSE
      }
    }else{
      cat(i, ids[i], " check the number of columns in the igem_obs sheet\n")
      flush.console()
      flag <- FALSE
    }
    
    if(flag){
      try(download.file(url, destfile, quiet = TRUE))
    }
    file.remove(tempfile)
  }
  
  
  ## ===============================================
  
  
  cat(i, "\n");flush.console()
}
```

``` {r}
filenames <- dir(path = destdir, pattern = "*.xlsx")


tmp1 <- list()
tmp2 <- list()
tmp3 <- list()
tmp4 <- list()

for(i in 1:length(filenames)) {
  destfile <- paste0(destdir, filenames[i])
  tmp1[[i]] <- read_excel(destfile, sheet = 1, skip = 0, col_names = T)
  tmp2[[i]] <- read_excel(destfile, sheet = 2, skip = 0, col_names = T)
  tmp3[[i]] <- read_excel(destfile, sheet = 3, skip = 0, col_names = T)
  tmp4[[i]] <- read_excel(destfile, sheet = 4, skip = 0, col_names = T)
}

igem_team <- do.call(bind_rows, tmp1)
igem_part <- do.call(bind_rows, tmp2)
igem_obs <- do.call(bind_rows, tmp3)
igem_device <- do.call(bind_rows, tmp4)
```
